baseURL = "https://opm.github.io/ResInsight-UserDocumentation/"
languageCode = "en-us"
title = "ResInsight"
theme = "learn"

[params]
disableSearch = false
disableHomeIcon = true
ordersectionsby = "weight"
disableShortcutsTitle = false


[[menu.shortcuts]]
	name = "<i class='fas fa-download'></i> Download"
	identifier = "download"
	url = "/project/download"
	weight = 20

[[menu.shortcuts]]
	name = "<i class='fas fa-info-circle'></i> About"
	identifier = "about"
	url = "/project/about"
	weight = 10

